kafka:
  group: message-service
  topic:
    message:
      message-notification
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
